### ISSUE TITLE
PDF Merger issue

### ISSUE THREAD

**Issue by inkandpaper-app** [TomRoush/PdfBox-Android#130]
First of all thank you for your valuable work! 

The merger seems to fail reading a jpeg image stream. For example the attached file becomes a blank page when merged. 
[page1.pdf](https://github.com/TomRoush/PdfBox-Android/files/1407102/page1.pdf)

Furthermore, please consider to avoid the method getPixel, which is painfully slow, in LosslessFactory. Using  getPixels instead would reduce by more than 1/2 the time needed to embed a png file in a pdf.

Best regards,

Francesco

**Comment by TomRoush** [comment]
1) Yup it seems that doesn't work. It isn't limited to jpeg images, other image types don't work either.
2) Thanks for letting me know. I'll get to work on replacing them wherever its used.

**Comment by TomRoush** [comment]
The issue has been fixed in the develop-2.0 branch and the fix will be available with the 2.0 release.

**Comment by lorenzos** [comment]
Great, looks fixed for me in develop-2.0.

For reference and future readers, to use it in your Android project, add the `maven { url "https://jitpack.io" }` repository in the project-level gradle, and then add the `implementation 'com.github.TomRoush:PdfBox-Android:develop-2.0-SNAPSHOT'` dependency in the app-level gradle instead of the standard one.

**Comment by PaoloBidello** [comment]
implementation 'com.github.TomRoush:PdfBox-Android:develop-2.0-SNAPSHOT' seems to be no longer available. 
When the 2.0 will be available?
At state of the art, can anyone suggest me, how to merge two pdfs with images correctly?
Thankyou so much.
Paolo

**Comment by lorenzos** [comment]
`com.github.TomRoush:PdfBox-Android:develop-2.0-SNAPSHOT` is missing for me too. Was the branch deleted? Were can we find it? Thanks.

**Comment by lorenzos** [comment]
I found the deleted branch still present in some forks:

- https://github.com/johngray1965/PdfBox-Android/tree/develop-2.0
- https://github.com/TechInSite/PdfBox-Android/tree/develop-2.0
- https://github.com/ngochai84/PdfBox-Android/tree/develop-2.0
- https://github.com/lucasnathan/PdfBox-Android/tree/develop-2.0
- https://github.com/m-awadi/PdfBox-Android/tree/develop-2.0

@PaoloBidello Looks like my project can be built again using one of these, for example: 

```implementation 'com.github.johngray1965:PdfBox-Android:develop-2.0-SNAPSHOT'```

**Comment by PaoloBidello** [comment]
Ciao Lorenzo.
The bad news is that the resources at 'com.github.TomRoush:PdfBox-Android:develop-2.0-SNAPSHOT' are no longer available.
The good news is that 25 days ago, Tom Roush released a new version of PDFBox for Android based on Apache PDFBox.
It is fully functional (I mean it manages correctly pdf with images) and updated to version 1.8.10.3.
We are currently developing our Chartarium app (https://www.studioenvisys.com/chartarium-for-android) which is based on these dependencies:
dependencies {
    implementation 'com.tom_roush:pdfbox-android:1.8.10.3'
}
You may want to find any more complete info at: https://github.com/TomRoush/PdfBox-Android
good luck!
and a big hug
Paolo

**Comment by lorenzos** [comment]
Good to know. I saw the recent release of 1.8.10.3, but I assumed it wouldn't include the PDF merging fix discussed here, since it were in a 2.0 (major) branch. Thanks for the info.

**Comment by lorenzos** [comment]
@markusressel What if you use `implementation 'com.github.johngray1965:PdfBox-Android:develop-2.0-SNAPSHOT'` instead (or one of the others)? Does it work?

**Comment by PaoloBidello** [comment]
@markusressel i have to confess that it is not clear to me which feature doesn't work. 
I can be sure that last release 1.8.10.3 let us merge two pdfs with images correctly, fixing a well known bug of the previous release.

**Comment by markusressel** [comment]
I haven't tested since I am not exactly fond of using some fork of a random guy in production.
I have looked into their repos though, and the `DCTFilter` seems to be absent in those `develop-2.0-SNAPSHOT` branches, while it is not in the `1.8.10.3` release.

**Comment by lorenzos** [comment]
@markusressel It looks like their branch is left as it were on the the original repo (there are no additional commits of them), anyway I understand you still have to trust they didn't tamper the commit history of their forks. That said, the `DCTFilter` is [not absent](https://github.com/johngray1965/PdfBox-Android/blob/develop-2.0/library/src/main/java/com/tom_roush/pdfbox/filter/DCTFilter.java) in the forks.

**Comment by markusressel** [comment]
Huh, you are right, the GitHub search is just bad then I guess.
But then again I still don't understand why the forks work. I get the exact log message that is part of this TCTFilter, and it makes sense that this would prevent images from getting processed since my images are JPEGs. Do you also get this log message, even when the merging works properly?

**Comment by lorenzos** [comment]
@markusressel No, I don't get that log messages.

**Comment by TomRoush** [comment]
Regarding the 2.0 branch, it was merged into master, which is why it was deleted. Starting with 2.0.0.0, snapshot version will be made available for any push to master. You can build from source or use a snapshot while the 2.0.0.0 release is finalized. To use the snapshot, use `implementation 'com.tom-roush:pdfbox-android:2.0.0.0-SNAPSHOT'` for the dependency and add `maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots/" }` to your repositories section.

You shouldn't be getting the DCTFilter log message at all. It sounds like it might be a problem that's specific to your PDF. There shouldn't be any issues for merging PDFs with JPEGs

**Comment by lorenzos** [comment]
@TomRoush Thanks for the update! So, if I understand correctly, the old `develop-2.0` branch was merged into master and then removed, but does the current 1.8.10.3 release include that merge or not?

**Comment by TomRoush** [comment]
The `develop-2.0` branch was merged into master, and the current 1.8.10.3 release does not contain that merge. That merge will be included in 2.0.0.0

**Comment by TomRoush** [comment]
Closing, 2.0.0.0 is released and has the fix

**Comment by markusressel** [comment]
It works, thx! 👍

**Comment by ninhkobietnau** [comment]
Thanks for update. It's work
